# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: docker pull registry.gitlab.com/pages/hugo:0.32.3

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  
before_script:
  - apk update
  - apk add rsync git
  - git config --global user.email "vkehayas@gmail.com"
  - git config --global user.name "Vassilis Kehayas"
  - git submodule foreach git pull origin master
  - rsync -ahvz staticman-comments/data/* data/

test:
  script:
  - hugo --buildFuture
  except:
  - master

pages:
  script:
  - hugo --buildFuture
  artifacts:
    paths:
    - public
  only:
  - master
